name = "Dracula"

[colors]
bg_start = "#282a36"
bg_mid = "#44475a"
bg_end = "#282a36"
title_start = "#f8f8f2"
title_mid = "#f1fa8c"
title_end = "#50fa7b"
subtitle = "#bd93f9"
meta = "#6272a4"
progress_bar_bg = "#44475a"
progress_bar_fill_start = "#50fa7b"
progress_bar_fill_mid = "#f1fa8c"
progress_bar_fill_end = "#ff5555"
progress_shimmer = "#f1fa8c"
separator = "#6272a4"
credits = "#6272a4"
terminal_bg = "#282a36"
terminal_stroke = "#44475a"
terminal_titlebar = "#44475a"
terminal_text = "#f8f8f2"
terminal_text_faded = "#6272a4"
terminal_prompt = "#50fa7b"
terminal_prompt_accent = "#ff79c6"
terminal_serving = "#f1fa8c"
terminal_cursor = "#ffb86c"
btn_red = "#ff5555"
btn_yellow = "#ffb86c"
btn_green = "#50fa7b"
badge_bg = "#44475a"
badge_stroke = "#50fa7b"
badge_text = "#f8f8f2"
pelican_stroke = "#50fa7b"
pelican_eye = "#ffb86c"
dots_color = "#50fa7b"
code_structure = "#f8f8f2"
decorative_bracket = "#ff79c6"
syn_cmd = "#50fa7b"
syn_pkg = "#ffb86c"
syn_flag = "#8be9fd"
syn_path = "#ff79c6"
vim_mode_bg = "#282a36"
vim_mode_stroke = "#6272a4"
vim_cursor = "#ffb86c"
vim_statusline_bg = "#313244"
vim_statusline_accent = "#45475a"
vim_statusline_fg = "#cdd6f4"
mini_vim_bg = "#282a36"
mini_vim_stroke = "#6272a4"
mini_vim_fg = "#f8f8f2"
mini_vim_ln = "#6272a4"
mini_vim_mode_bg = "#50fa7b"
mini_vim_mode_fg = "#282a36"
vim_key_bg = "#44475a"
vim_key_fg = "#f8f8f2"
sysinfo_fg = "#cdd6f4"
sysinfo_label = "#6272a4"
sysinfo_ascii = "#f1fa8c"
bash_user = "#50fa7b"
bash_host = "#ff79c6"
bash_path = "#f1fa8c"
bash_prompt_symbol = "#ffffff"
bash_cursor = "#ffb86c"
ascii_logo_color = "#f1fa8c"
pkg_bg = "#44475a"
pkg_fg = "#f8f8f2"
pkg_stroke = "#6272a4"
vim_editor_bg = "#1e1e2e"
vim_editor_stroke = "#313244"
vim_editor_titlebar = "#45475a"
vim_editor_title_fg = "#cdd6f4"
vim_editor_fg = "#f8f8f2"
vim_editor_ln = "#6272a4"
vim_editor_mode_bg = "#50fa7b"
vim_editor_mode_fg = "#282a36"
vim_editor_status_bg = "#313244"
vim_editor_status_fg = "#cdd6f4"
vim_editor_cursor = "#ffb86c"
syn_comment = "#6272a4"
syn_keyword = "#ff79c6"
syn_string = "#f1fa8c"
syn_bool = "#bd93f9"
syn_number = "#bd93f9"
syn_default = "#f8f8f2"

[layout]
title_font_size = 68
subtitle_font_size = 38

[pygments]
keyword = "#ff79c6"
function = "#50fa7b"
class = "#8be9fd"
variable = "#f8f8f2"
string = "#f1fa8c"
docstring = "#6272a4"
comment = "#6272a4"
number = "#bd93f9"
operator = "#ff79c6"
default = "#f8f8f2"
