
name = "Gruvbox Dark"

[colors]
bg_start = "#282828"
bg_mid = "#3c3836"
bg_end = "#1d2021"
title_start = "#fabd2f"
title_mid = "#83a598"
title_end = "#b8bb26"
subtitle = "#ebdbb2"
meta = "#7c6f64"
progress_bar_bg = "#3c3836"
progress_bar_fill_start = "#b8bb26"
progress_bar_fill_mid = "#fabd2f"
progress_bar_fill_end = "#fb4934"
progress_shimmer = "#ebdbb2"
separator = "#504945"
credits = "#7c6f64"
terminal_bg = "#282828"
terminal_stroke = "#3c3836"
terminal_titlebar = "#3c3836"
terminal_text = "#ebdbb2"
terminal_text_faded = "#7c6f64"
terminal_prompt = "#b8bb26"
terminal_prompt_accent = "#83a598"
terminal_serving = "#fabd2f"
terminal_cursor = "#fb4934"
btn_red = "#fb4934"
btn_yellow = "#fabd2f"
btn_green = "#b8bb26"
badge_bg = "#3c3836"
badge_stroke = "#83a598"
badge_text = "#ebdbb2"
pelican_stroke = "#83a598"
pelican_eye = "#fabd2f"
dots_color = "#83a598"
code_structure = "#ebdbb2"
decorative_bracket = "#d3869b"
syn_cmd = "#b8bb26"
syn_pkg = "#fabd2f"
syn_flag = "#83a598"
syn_path = "#d3869b"
social_icon_color = "#83a598"
vim_mode_bg = "#282828"
vim_mode_stroke = "#3c3836"
vim_cursor = "#fb4934"
vim_statusline_bg = "#3c3836"
vim_statusline_accent = "#504945"
vim_statusline_fg = "#ebdbb2"
mini_vim_bg = "#282828"
mini_vim_stroke = "#3c3836"
mini_vim_fg = "#ebdbb2"
mini_vim_ln = "#7c6f64"
mini_vim_mode_bg = "#b8bb26"
mini_vim_mode_fg = "#282828"
vim_key_bg = "#3c3836"
vim_key_fg = "#ebdbb2"
sysinfo_fg = "#ebdbb2"
sysinfo_label = "#7c6f64"
sysinfo_ascii = "#83a598"
bash_user = "#b8bb26"
bash_host = "#d3869b"
bash_path = "#fabd2f"
bash_prompt_symbol = "#ebdbb2"
bash_cursor = "#fb4934"
ascii_logo_color = "#83a598"
pkg_bg = "#3c3836"
pkg_fg = "#ebdbb2"
pkg_stroke = "#504945"
vim_editor_bg = "#282828"
vim_editor_stroke = "#3c3836"
vim_editor_titlebar = "#3c3836"
vim_editor_title_fg = "#ebdbb2"
vim_editor_fg = "#ebdbb2"
vim_editor_ln = "#7c6f64"
vim_editor_mode_bg = "#b8bb26"
vim_editor_mode_fg = "#282828"
vim_editor_status_bg = "#3c3836"
vim_editor_status_fg = "#ebdbb2"
vim_editor_cursor = "#fb4934"
syn_comment = "#7c6f64"
syn_keyword = "#d3869b"
syn_string = "#b8bb26"
syn_bool = "#fabd2f"
syn_number = "#fe8019"
syn_default = "#ebdbb2"
