from __future__ import annotations
from ..base import BaseComponent

class Component(BaseComponent):
    config_schema = {}
    z_index = 0
    section_name = None
    description = 'Background gradients, patterns, and vignette'
    component_id = 'background'

    def defs(self) -> str:
        c = self.col

        def g(k, default):
            return c.get(k, default)
        progress_defs = f'''\n    <linearGradient id="progressGradLow" x1="0%" y1="0%" x2="100%" y2="0%">\n      <stop offset="0%" stop-color="{g('progress_bar_fill_start', '#a6e3a1')}" />\n      <stop offset="100%" stop-color="{g('progress_shimmer', '#cdd6f4')}" />\n    </linearGradient>\n    <linearGradient id="progressGradMid" x1="0%" y1="0%" x2="100%" y2="0%">\n      <stop offset="0%" stop-color="{g('progress_bar_fill_mid', '#f9e2af')}" />\n      <stop offset="100%" stop-color="{g('progress_shimmer', '#cdd6f4')}" />\n    </linearGradient>\n    <linearGradient id="progressGradHigh" x1="0%" y1="0%" x2="100%" y2="0%">\n      <stop offset="0%" stop-color="{g('progress_bar_fill_end', '#f38ba8')}" />\n      <stop offset="100%" stop-color="{g('progress_shimmer', '#cdd6f4')}" />\n    </linearGradient>\n'''
        return f'''\n    <!-- Background gradients -->\n    <linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">\n      <stop offset="0%" stop-color="{g('bg_start', '#0d1117')}" />\n      <stop offset="50%" stop-color="{g('bg_mid', '#161b22')}" />\n      <stop offset="100%" stop-color="{g('bg_end', '#0d1117')}" />\n    </linearGradient>\n    <radialGradient id="vignette" cx="50%" cy="50%" r="70%">\n      <stop offset="50%" stop-color="#000" stop-opacity="0" />\n      <stop offset="100%" stop-color="#000" stop-opacity="0.35" />\n    </radialGradient>\n    <linearGradient id="keyLight" x1="0%" y1="0%" x2="100%" y2="100%">\n      <stop offset="0%" stop-color="#ffffff" stop-opacity="0.06" />\n      <stop offset="100%" stop-color="#000000" stop-opacity="0" />\n    </linearGradient>\n\n    <!-- Patterns -->\n    <pattern id="dots" x="0" y="0" width="20" height="20" patternUnits="userSpaceOnUse">\n      <circle cx="2" cy="2" r="1" fill="{g('dots_color', '#94a3b8')}" opacity="0.12" />\n    </pattern>\n    <pattern id="grid" x="0" y="0" width="30" height="30" patternUnits="userSpaceOnUse">\n      <path d="M 30 0 L 0 0 0 30" fill="none" stroke="{g('dots_color', '#94a3b8')}" stroke-width="0.5" opacity="0.06" />\n    </pattern>\n    <pattern id="scanlines" width="4" height="4" patternUnits="userSpaceOnUse">\n      <line x1="0" y1="2" x2="4" y2="2" stroke="#ffffff" stroke-width="1" opacity="0.03" />\n    </pattern>\n\n    <!-- Title gradient & filters -->\n    <linearGradient id="titleGrad" x1="0%" y1="0%" x2="100%" y2="0%">\n      <stop offset="0%" stop-color="{g('title_start', '#e0eafc')}" />\n      <stop offset="50%" stop-color="{g('title_mid', '#b8c6db')}" />\n      <stop offset="100%" stop-color="{g('title_end', '#94a3b8')}" />\n    </linearGradient>\n    <filter id="titleShadow" x="-5%" y="-5%" width="110%" height="110%">\n      <feDropShadow dx="0" dy="2" stdDeviation="3" flood-color="#000000" flood-opacity="0.4" />\n    </filter>\n    <filter id="titleGlow" x="-20%" y="-20%" width="140%" height="140%">\n      <feGaussianBlur in="SourceAlpha" stdDeviation="4" result="blur" />\n      <feFlood flood-color="{g('title_glow', '#94a3b8')}" flood-opacity="0.25" result="color" />\n      <feComposite in="color" in2="blur" operator="in" result="glow" />\n      <feMerge>\n        <feMergeNode in="glow" />\n        <feMergeNode in="SourceGraphic" />\n      </feMerge>\n    </filter>\n\n    <!-- Terminal glow -->\n    <filter id="termGlow" x="-10%" y="-10%" width="120%" height="120%">\n      <feGaussianBlur in="SourceAlpha" stdDeviation="12" result="blur" />\n      <feFlood flood-color="{g('terminal_glow', '#94a3b8')}" flood-opacity="0.15" result="color" />\n      <feComposite in="color" in2="blur" operator="in" result="glow" />\n      <feMerge>\n        <feMergeNode in="glow" />\n        <feMergeNode in="SourceGraphic" />\n      </feMerge>\n    </filter>\n\n    <!-- Progress gradients -->\n    {progress_defs}\n'''.strip()

    def render(self) -> str:
        return f'\n  <!-- Base background -->\n  <rect width="{self.w}" height="{self.h}" fill="url(#bg)" />\n  <rect width="{self.w}" height="{self.h}" fill="url(#grid)" />\n  <rect width="{self.w}" height="{self.h}" fill="url(#dots)" />\n\n  <!-- Vignette + key light -->\n  <rect width="{self.w}" height="{self.h}" fill="url(#vignette)" pointer-events="none" />\n  <rect width="{self.w}" height="{self.h}" fill="url(#keyLight)" pointer-events="none" />\n'.rstrip()